# Databricks notebook source
# MAGIC %md
# MAGIC # 📊 Ad-Hoc Pipeline Exploration Notebook
# MAGIC 
# MAGIC Use this notebook to interactively explore, query, and visualize the data generated by the Spark Declarative Pipeline.
# MAGIC 
# MAGIC > **Note**: This notebook is designed for exploratory data analysis (EDA) and is **not** executed as part of the formal pipeline DAG run.

# COMMAND ----------

# MAGIC %md
# MAGIC ### 1. Setup Workspace Path
# MAGIC We append the pipeline's root directory to the system path so that we can easily import utility functions.

# COMMAND ----------

import sys
import os

# Appends workspace directory dynamically to Python system path
sys.path.append(os.path.abspath(".."))

# COMMAND ----------

# MAGIC %md
# MAGIC ### 2. Verify and Query Materialized Gold Layer Sales
# MAGIC Run a SQL query against the daily revenue aggregation table materialized by `first_dag.py` in the Target catalog.
# MAGIC 
# MAGIC _Ensure you run the pipeline once to materialize the tables before executing this query!_

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Fetch daily accumulated revenue for dashboards
# MAGIC SELECT 
# MAGIC   date, 
# MAGIC   total_revenue 
# MAGIC FROM 
# MAGIC   sdp_catalog.target.cur_sales 
# MAGIC ORDER BY 
# MAGIC   date DESC;